spring:
    application:
        name: example-web-api
    profiles.include:
        - infra
        - infra-secret
    api:
        prefix: "/api"
        version: "v1"

client:
    origin: "http://localhost:3000"
